### PR TITLE
Added improved (IMHO) recently-updated script.

### PR DESCRIPTION
**Pull request by suetanvil**
The script findmod2.pl is a rewrite of the the existing scripts and
templates in readable, dependency-free Perl5.  In addition to adding
bells and whistles, findmod2.pl will search each user's entire
public_html directory for activity rather than just the index.html
file.

### CODE REVIEW

**Comment by suetanvil** [comment]
I started on this because the existing findmod wasn't finding my blog updates since they don't modify index.html.

**Comment by pfhawkins** [comment]
:+1: :tada:

**Comment by ftrain** [comment]
Yah, no reason to wait, might as well merge.

**Comment by suetanvil** [comment]
@delfuego, I hear you about searching the entire tree.  The current results tend to be dominated by automatically-generated pages right now.

I think it comes down to the culture of the site; do you expect everything in your public_html to be viewed?

Of course, there's always a simple technical fix: just optionally exclude everything that changes too often.

**Pull request merged**
